import { useEffect, useState } from "react";
import { createAnnouncement, deleteAnnouncement, fetchAnnouncements, sendAnnouncement } from "../services/adminApi";
import { TRINIDAD_BARANGAYS } from "../config/community";
import { EmptyRow, StatCard, StatusBadge, btnGhost, btnPrimary, tdClass, tdStrongClass, theadClass } from "./ui";

const EMPTY = { title: "", body: "", audience: "all", barangay: "", status: "draft", scheduled_at: "" };
const AUDIENCES = { all: "All members", verified: "Verified residents", barangay: "Trinidad barangay", admins: "Admins" };

export default function NotificationsManager() {
  const [data, setData] = useState(null); const [form, setForm] = useState(EMPTY);
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = () => fetchAnnouncements().then(setData).catch((e) => setError(e.message));
  useEffect(() => { load(); }, []);
  const submit = async (event) => {
    event.preventDefault(); setBusy(true); setError("");
    try { await createAnnouncement(form); setForm(EMPTY); setOpen(false); await load(); }
    catch (e) { setError(e.message); } finally { setBusy(false); }
  };
  const act = async (fn) => { try { await fn(); await load(); } catch (e) { setError(e.message); } };
  return <section className="space-y-5">
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    <div className="grid gap-4 sm:grid-cols-3"><StatCard icon="📣" label="Total sent" value={data?.summary?.sent} accent /><StatCard icon="🗓️" label="Scheduled" value={data?.summary?.scheduled} /><StatCard icon="📝" label="Drafts" value={data?.summary?.drafts} /></div>
    <div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-extrabold text-emerald-950">Announcements</h2><p className="text-sm text-stone-500">Broadcast updates to the Trinidad community.</p></div><button className={btnPrimary} onClick={() => setOpen(true)}>+ New Announcement</button></div>
    <div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className={theadClass}><tr><th className="px-4 py-3">Announcement</th><th className="px-4 py-3">Audience</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-stone-100">
      {!data ? <EmptyRow colSpan={4}>Loading announcements…</EmptyRow> : data.announcements?.length === 0 ? <EmptyRow colSpan={4}>No announcements yet. Create one to reach members.</EmptyRow> : data.announcements.map((item) => <tr key={item.id}><td className={tdStrongClass}><div>{item.title}</div><div className="text-xs font-normal text-stone-400">{item.updated_at || "—"}</div></td><td className={tdClass}>{AUDIENCES[item.audience]}{item.barangay ? ` · ${item.barangay}` : ""}</td><td className={tdClass}><StatusBadge tone={item.status === "sent" ? "success" : item.status === "scheduled" ? "info" : "warn"}>{item.status}</StatusBadge></td><td className={`${tdClass} text-right`}>{item.status !== "sent" && <button className={btnGhost} onClick={() => act(() => sendAnnouncement(item.id))}>Send</button>}{" "}<button className="text-xs font-semibold text-red-700 hover:underline" onClick={() => window.confirm(`Delete "${item.title}"?`) && act(() => deleteAnnouncement(item.id))}>Delete</button></td></tr>)}
    </tbody></table></div></div>
    {open && <div className="fixed inset-0 z-20 grid place-items-center bg-emerald-950/40 p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold text-emerald-950">New announcement</h2><button type="button" onClick={() => setOpen(false)}>✕</button></div><label className="block text-sm font-semibold">Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2" /></label><label className="block text-sm font-semibold">Message<textarea required rows="4" value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2" /></label><label className="block text-sm font-semibold">Audience<select value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value, barangay: "" })} className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2">{Object.entries(AUDIENCES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{form.audience === "barangay" && <label className="block text-sm font-semibold">Barangay<select required value={form.barangay} onChange={(e) => setForm({ ...form, barangay: e.target.value })} className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"><option value="">Select barangay</option>{TRINIDAD_BARANGAYS.map((barangay) => <option key={barangay}>{barangay}</option>)}</select></label>}<label className="block text-sm font-semibold">Delivery<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"><option value="draft">Save draft</option><option value="scheduled">Schedule</option><option value="sent">Send now</option></select></label>{form.status === "scheduled" && <label className="block text-sm font-semibold">Send at<input required type="datetime-local" value={form.scheduled_at} onChange={(e) => setForm({ ...form, scheduled_at: e.target.value })} className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2" /></label>}<div className="flex justify-end gap-2"><button type="button" className={btnGhost} onClick={() => setOpen(false)}>Cancel</button><button disabled={busy} className={btnPrimary}>{busy ? "Saving…" : "Save announcement"}</button></div></form></div>}
  </section>;
}
